[Settings]
# Team to use for marking plays that are in the game plan.
Team = Denver

# Path to the directory containing the play files.
# Default is C:\SIERRA\FbPro98\PNFL
PlayPath = E:\SIERRA\FbPro98\PNFL\

# Indicates whether pdb_to_excel should calculate the total stats for each
# play by totaling the data from all teams.
# Choices are: Yes or No
# Yes: Total stats for each play are included in the results.
# No: Total stats are not included in the results.
# Default is Yes.
CalculateTotalStats = Yes

[AdditionalColumns]
RunFumblePercentage = Yes
RunTouchdownPercentage = Yes
PassInterceptionPercentage = Yes
PassSackPercentage = Yes
PassTouchdownPercentage = Yes
DefenseTurnoverPercentage = Yes
DefenseSackPercentage = Yes
DefenseOffTdPercentage = Yes
