[Settings]
# Team name for marking plays that are in the game plan.
# Set this to your team's city name (e.g. Denver, Green Bay, Miami).
Team =

# Path to the directory containing the play files.
PlayPath = C:\SIERRA\FbPro98\PNFL

# Calculate total stats for each play by totaling data from all teams.
# Choices: Yes or No
CalculateTotalStats = Yes

[AdditionalColumns]
RunFumblePercentage = Yes
RunTouchdownPercentage = Yes
PassInterceptionPercentage = Yes
PassSackPercentage = Yes
PassTouchdownPercentage = Yes
DefenseTurnoverPercentage = Yes
DefenseSackPercentage = Yes
DefenseOffTdPercentage = Yes
